In [1]:
import numpy as np
from noise_seeds import generate_noise
from PIL import Image

In [2]:
black_frames = np.full((144, 256), fill_value = 0)

In [3]:
dynamic3 = generate_noise('dynamic', 1, 3)
dynamic3 = np.squeeze(dynamic3)

In [4]:
final_array = (black_frames + dynamic3)

In [5]:
final_array

array([[-1.93823671e-03, -2.82569361e+00,  4.53200847e-01, ...,
        -2.82481651e+00,  3.94044460e+00,  1.79602811e+00],
       [-2.86557440e-01, -3.16823459e+00,  2.23278048e+00, ...,
         2.08299178e-01, -1.52665096e+00, -6.33851126e-01],
       [-2.25560295e+00,  4.38298936e+00,  3.50932977e+00, ...,
         2.10211789e+00, -5.52979246e+00, -4.58650904e+00],
       ...,
       [-1.64665198e+00, -2.61901201e+00,  1.75538649e+00, ...,
        -1.73206538e+00,  1.11985395e+00,  1.60585652e+00],
       [ 4.00208513e-01, -3.33190102e+00,  3.62413833e+00, ...,
        -5.54796446e+00,  6.33781219e-01,  3.19893456e+00],
       [ 3.02860432e+00,  3.16277477e+00,  2.02857871e+00, ...,
        -2.21972054e+00,  6.01459221e+00, -5.86330003e-01]])

In [6]:
final_array = np.round(final_array)

In [7]:
final_array

array([[-0., -3.,  0., ..., -3.,  4.,  2.],
       [-0., -3.,  2., ...,  0., -2., -1.],
       [-2.,  4.,  4., ...,  2., -6., -5.],
       ...,
       [-2., -3.,  2., ..., -2.,  1.,  2.],
       [ 0., -3.,  4., ..., -6.,  1.,  3.],
       [ 3.,  3.,  2., ..., -2.,  6., -1.]])

In [8]:
final_image = np.clip(final_array, a_min = 0, a_max = 255)

In [9]:
final_image.shape

(144, 256)

In [10]:
final_image

array([[0., 0., 0., ..., 0., 4., 2.],
       [0., 0., 2., ..., 0., 0., 0.],
       [0., 4., 4., ..., 2., 0., 0.],
       ...,
       [0., 0., 2., ..., 0., 1., 2.],
       [0., 0., 4., ..., 0., 1., 3.],
       [3., 3., 2., ..., 0., 6., 0.]])

In [11]:
image = Image.fromarray(final_image)

In [12]:
image.show()

In [ ]:
np.max(black_frames + dynamic3)

np.float64(12.329142395758344)