In [1]:
import numpy as np
from noise_seeds import generate_noise
from PIL import Image


# august 11th

In [2]:
black_frames = np.full((144, 256), fill_value = 0)

In [3]:
dynamic3 = generate_noise('dynamic', 1, 3)
dynamic3 = np.squeeze(dynamic3)

In [4]:
final_array = (black_frames + dynamic3)

In [5]:
final_array

array([[-1.39106973,  2.93475534,  0.97061978, ...,  2.89991911,
         1.13355965, -1.10606294],
       [-0.2641801 , -3.19742117,  1.21731814, ..., -4.18216912,
        -6.94544732, -3.62635224],
       [-3.35312715,  3.69394556,  2.34711808, ...,  0.03529587,
         1.48389353, -1.3159068 ],
       ...,
       [-4.27844083,  4.3928105 , -2.26643658, ...,  0.58566629,
         2.82686912,  7.00445435],
       [-0.37785696, -2.64463703,  2.90684498, ...,  1.24718284,
         3.55842674,  0.44063011],
       [ 0.08391263, -1.77024955,  3.89227117, ..., -0.98394486,
        -5.46384776, -7.55160245]])

In [6]:
final_array = np.round(final_array)

In [7]:
final_array

array([[-1.,  3.,  1., ...,  3.,  1., -1.],
       [-0., -3.,  1., ..., -4., -7., -4.],
       [-3.,  4.,  2., ...,  0.,  1., -1.],
       ...,
       [-4.,  4., -2., ...,  1.,  3.,  7.],
       [-0., -3.,  3., ...,  1.,  4.,  0.],
       [ 0., -2.,  4., ..., -1., -5., -8.]])

In [8]:
final_image = np.clip(final_array, a_min = 0, a_max = 255)

In [9]:
final_image

array([[0., 3., 1., ..., 3., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 4., 2., ..., 0., 1., 0.],
       ...,
       [0., 4., 0., ..., 1., 3., 7.],
       [0., 0., 3., ..., 1., 4., 0.],
       [0., 0., 4., ..., 0., 0., 0.]])

In [10]:
final_astype = final_image.astype('uint8')
final_astype

array([[0, 3, 1, ..., 3, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 4, 2, ..., 0, 1, 0],
       ...,
       [0, 4, 0, ..., 1, 3, 7],
       [0, 0, 3, ..., 1, 4, 0],
       [0, 0, 4, ..., 0, 0, 0]], dtype=uint8)

In [11]:
image = Image.fromarray(final_image)

In [12]:
image.show()

In [13]:
np.max(black_frames + dynamic3)

np.float64(13.08144848736626)

# august 13th

In [22]:
# in real code we now d3_labels from np.unique() on region label output from predictions
d3_labels = [1,2,3,4]

string_path = 'fnn//input_noise//saved_inputs_outputs//predictions_july21//'

for noise in ['c3', 'c15', 'c30', 'd3', 'd15', 'd30', 'dbin', 'cbin', 'no_noise']:
    for type_noise in ['_sum', '_mean', '_var', '_labels']:
        file_name = string_path + noise + type_noise + '.npy'
        globals()[file_name] = np.load(file_name)

# load predictions by region
for region in d3_labels:
    for noise in ['c3', 'c15', 'c30', 'd3', 'd15', 'd30', 'dbin', 'cbin', 'no_noise']:
        for type_noise in ['_sum', '_mean', '_var']:
            array_name = string_path + noise + type_noise + '_r' + str(region) + '.npy'
            globals()[array_name] = np.load(array_name)

In [31]:
c3_mean_labels

NameError: name 'c3_mean_labels' is not defined

In [14]:
scatter_means = [[d3_mean_r1, d15_mean_r1, d30_mean_r1, dbin_mean_r1],
                 [d3_mean_r2, d15_mean_r2, d30_mean_r2, dbin_mean_r2],
                 [d3_mean_r3, d15_mean_r3, d30_mean_r3, dbin_mean_r3],
                 [d3_mean_r4, d15_mean_r4, d30_mean_r4, dbin_mean_r4]]

scatter_vars = [[d3_var_r1, d15_var_r1, d30_var_r1, dbin_var_r1],
               [d3_var_r2, d15_var_r2, d30_var_r2, dbin_var_r2],
               [d3_var_r3, d15_var_r3, d30_var_r3, dbin_var_r3],
               [d3_var_r4, d15_var_r4, d30_var_r4, dbin_var_r4]]
scatter_means = [[d15_mean_r1, d30_mean_r1, dbin_mean_r1],
                 [d15_mean_r2, d30_mean_r2, dbin_mean_r2],
                 [d15_mean_r3, d30_mean_r3, dbin_mean_r3],
                 [d15_mean_r4, d30_mean_r4, dbin_mean_r4]]

scatter_vars = [[d15_var_r1, d30_var_r1, dbin_var_r1],
               [d15_var_r2, d30_var_r2, dbin_var_r2],
               [d15_var_r3, d30_var_r3, dbin_var_r3],
               [d15_var_r4, d30_var_r4, dbin_var_r4]]

NameError: name 'd3_mean_r1' is not defined

In [ ]:
from visualizations import 