In [1]:
import numpy as np
from noise_seeds import generate_noise
from PIL import Image

In [2]:
black_frames = np.full((144, 256), fill_value = 0)

In [3]:
dynamic3 = generate_noise('dynamic', 1, 3)
dynamic3 = np.squeeze(dynamic3)

In [6]:
final_array = (black_frames + dynamic3)

In [7]:
final_array

array([[ 1.19045123, -2.50733319,  1.93877382, ...,  1.58551007,
         1.06217636, -5.55287134],
       [-3.08549268, -1.33934837, -7.04106119, ...,  0.51171361,
         0.52942841, -5.33251375],
       [ 2.52944378, -0.51586621,  0.36132037, ..., -1.77133951,
         3.689994  , -2.64585199],
       ...,
       [-8.1611736 , -3.80633119,  0.63113154, ..., -5.97954406,
        -0.23634348, -1.21720592],
       [-3.02335227,  0.07962573, -0.6913421 , ..., -0.25162281,
         1.37076162, -1.14700811],
       [ 0.49687561, -6.95469884, -0.26309095, ...,  3.42028068,
        -3.84606464,  1.62790285]])

In [9]:
final_array = np.round(final_array)

In [10]:
final_array

array([[ 1., -3.,  2., ...,  2.,  1., -6.],
       [-3., -1., -7., ...,  1.,  1., -5.],
       [ 3., -1.,  0., ..., -2.,  4., -3.],
       ...,
       [-8., -4.,  1., ..., -6., -0., -1.],
       [-3.,  0., -1., ..., -0.,  1., -1.],
       [ 0., -7., -0., ...,  3., -4.,  2.]])

In [11]:
final_image = np.clip(final_array, a_min = 0, a_max = 255)

In [12]:
final_image.shape

(144, 256)

In [13]:
final_image

array([[1., 0., 2., ..., 2., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [3., 0., 0., ..., 0., 4., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 3., 0., 2.]])

In [14]:
image = Image.fromarray(final_image)

In [15]:
image.show()

In [ ]:
final

array([[  0,   0,   0, ...,   1,   3,   0],
       [  0, 255,   0, ..., 255, 252,   0],
       [  3,   1, 251, ...,   0, 254,   1],
       ...,
       [  5, 252,   0, ...,   2,   2,   0],
       [  0,   0,   0, ...,   2,   0,   1],
       [  0, 255, 251, ...,   3,   1,   3]], dtype=uint8)

In [ ]:
np.max(black_frames + dynamic3)

np.float64(12.329142395758344)